import "./globals.css";

import { Kaushan_Script, Montserrat } from "next/font/google";

import Header from "@/components/Header";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import classNames from "classnames";

const inter = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const kaushan = Kaushan_Script({
  subsets: ["latin"],
  variable: "--font-kaushan",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Daniel Zavala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cls = classNames([inter.className, kaushan.variable]);
  return (
    <html lang="en">
      <body className={cls}>
        <main className={"page text-white"}>
          <Header />
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
